let allMusic = [
  {
    name: "3107-2",
    artist: "W/N, Duongg, Nau",
    img: "sound3107-2",
    src: "sound3107-2",
  },
  {
    name: "Bao tiền một mớ bình yên",
    artist: "14 Casper, Bon Nghiêm",
    img: "bao-tien-mot-mo-binh-yen",
    src: "bao-tien-mot-mo-binh-yen",
  },
  {
    name: "Chờ đợi có đáng sợ",
    artist: "Andiez",
    img: "cho-doi-co-dang-so",
    src: "cho-doi-co-dang-so",
  },
  {
    name: "Đã lỡ yêu em nhiều",
    artist: "Justatee",
    img: "da-lo-yeu-em-nhieu",
    src: "da-lo-yeu-em-nhieu",
  },
  {
    name: "Forget me now",
    artist: "Fishy, Trí Dũng",
    img: "forget-me-now",
    src: "forget-me-now",
  },
  {
    name: "Hẹn em kiếp sau  ",
    artist: "Duy Phúc, Lã, TiB",
    img: "hen-em-kiep-sau",
    src: "hen-em-kiep-sau",
  },
  {
    name: "Hẹn em ở lần yêu thứ 2",
    artist: "Nguyenn, Đặng Tuấn Vũ",
    img: "hen-em-o-lan-yeu-thu-2",
    src: "hen-em-o-lan-yeu-thu-2",
  },
  {
    name: "Nàng thơ",
    artist: "Hoàng Dũng",
    img: "nang-tho",
    src: "nang-tho",
  },
  {
    name: "Như anh đã thấy em",
    artist: "PhucXp, Freak D",
    img: "nhu-anh-da-thay-em",
    src: "nhu-anh-da-thay-em",
  },
  {
    name: "Sinh ra đã là thứ đối lập nhau",
    artist: "Emcee L, Da LAB, Badbies",
    img: "sinh-ra-da-la-thu-doi-lap-nhau",
    src: "sinh-ra-da-la-thu-doi-lap-nhau",
  },
  {
    name: "Suýt nữa thì",
    artist: "Andiez",
    img: "suyt-nua-thi",
    src: "suyt-nua-thi",
  },
  {
    name: "thằng điên",
    artist: "Justatee, Phương Ly",
    img: "thang-dien",
    src: "thang-dien",
  },
  {
    name: "Chỉ muốn bên em lúc này",
    artist: "Orinn, Huy Vạc",
    img: "chi-muon-ben-em-luc-nay",
    src: "chi-muon-ben-em-luc-nay",
  },
  {
    name: "Bầu trời mới",
    artist: "Da Lab, Minh Tốc, Lam",
    img: "bau-troi-moi",
    src: "bau-troi-moi",
  },
  {
    name: "Blue",
    artist: "Yung Kai",
    img: "blue",
    src: "blue",
  },
  {
    name: "Car's Outside",
    artist: "James Arthur",
    img: "car-outside",
    src: "car-outside",
  },
  {
    name: "Chạy ngay đi",
    artist: "Sơn Tùng MTP",
    img: "chay-ngay-di",
    src: "chay-ngay-di",
  },
  {
    name: "Cheating on you",
    artist: "Justin Bieber",
    img: "cheating-on-you",
    src: "cheating-on-you",
  },
  {
    name: "Chỉ là muốn nói",
    artist: "Khải, Thắng Nguyễn",
    img: "chi-la-muon-noi",
    src: "chi-la-muon-noi",
  },
  {
    name: "Có ai ở đây không",
    artist: "14 Casper, Bon Nghiêm",
    img: "co-ai-o-day-khong",
    src: "co-ai-o-day-khong",
  },
  {
    name: "Mỉm cười nơi chín suối",
    artist: "Lady Gaga, Bruno Mars",
    img: "die-with-a-smile",
    src: "die-with-a-smile",
  },
  {
    name: "Dù cho tận thế",
    artist: "Erik",
    img: "du-cho-tan-the",
    src: "du-cho-tan-the",
  },
  {
    name: "Đừng vì anh mà khóc",
    artist: "Quang Hùng MasterD",
    img: "dung-vi-anh-ma-khoc",
    src: "dung-vi-anh-ma-khoc",
  },
  {
    name: "Một đời",
    artist: "14 Casper, Bon Nghiêm",
    img: "mot-doi",
    src: "mot-doi",
  },
  {
    name: "Somebody's Pleasure",
    artist: "Aziz Hedra",
    img: "somebody-pleasure",
    src: "somebody-pleasure",
  },
  {
    name: "Thật ra em chẳng thương anh vậy đâu",
    artist: "Nguyenn, Đặng Tuấn Vũ",
    img: "that-ra-em-chang-thuong-anh-vay-dau",
    src: "that-ra-em-chang-thuong-anh-vay-dau",
  },
  {
    name: "We don't talk anymore",
    artist: "Justin Bieber",
    img: "we-dont-talk-anymore",
    src: "we-dont-talk-anymore",
  },
  {
    name: "Yêu một người có lẽ",
    artist: "Miu Lê, Lou Hoàng",
    img: "yeu-mot-nguoi-co-le",
    src: "yeu-mot-nguoi-co-le",
  },
];
